package cwlib.enums;

/**
 * Revisions for when parts were added to the game.
 */
public class PartHistory {
    public static final int BODY = 0x1;
    public static final int JOINT = 0x2;
    public static final int WORLD = 0x3;
    public static final int RENDER_MESH = 0x4;
    public static final int POS = 0x5;
    public static final int TRIGGER = 0x6;
    public static final int TRIGGER_EFFECTOR = 0x7;
    public static final int PAINT = 0x8;
    public static final int YELLOWHEAD = 0x9;
    public static final int AUDIO_WORLD = 0xa;
    public static final int ANIMATION = 0xb;
    public static final int GENERATED_MESH = 0xc;
    public static final int PARTICLE_CLUMP = 0xd;
    public static final int PARTICLE_EMITTER = 0xe;
    public static final int CAMERA_ZONE = 0xf;
    public static final int LEVEL_SETTINGS = 0x10;
    public static final int SPRITE_LIGHT = 0x11;
    public static final int KEYFRAMED_POSITION = 0x12;
    public static final int CAMERA = 0x13;
    public static final int SCRIPT_NAME = 0x14;
    public static final int CREATURE = 0x15;
    public static final int CHECKPOINT = 0x16;
    public static final int STICKERS = 0x17;
    public static final int DECORATIONS = 0x18;
    public static final int SCRIPT = 0x19;
    public static final int SHAPE = 0x1a;
    public static final int EFFECTOR = 0x1b;
    public static final int EMITTER = 0x1c;
    public static final int REF = 0x1d;
    public static final int METADATA = 0x1e;
    public static final int COSTUME = 0x1f;
    public static final int PARTICLE_EMITTER_2 = 0x20;
    public static final int CAMERA_TWEAK = 0x21;
    public static final int SWITCH = 0x22;
    public static final int SWITCH_KEY = 0x23;
    public static final int GAMEPLAY_DATA = 0x24;
    public static final int ENEMY = 0x25;
    public static final int GROUP = 0x26;
    public static final int PHYSICS_TWEAK = 0x27;
    public static final int NPC = 0x28;
    public static final int SWITCH_INPUT = 0x29;
    public static final int MICROCHIP = 0x2a;
    public static final int MATERIAL_TWEAK = 0x2b;
    public static final int MATERIAL_OVERRIDE = 0x2c;
    public static final int INSTRUMENT = 0x2d;
    public static final int SEQUENCER = 0x2e;
    public static final int CONTROLINATOR = 0x2f;
    public static final int POPPET_POWERUP = 0x30;
    public static final int POCKET_ITEM = 0x31;
    public static final int CREATOR_ANIM = 0x32;
    public static final int TRANSITION = 0x33;
    public static final int FADER = 0x34;
    public static final int ANIMATION_TWEAK = 0x35;
    public static final int WIND_TWEAK = 0x36;
    public static final int POWER_UP = 0x37;
    public static final int HUD_ELEM = 0x38;
    public static final int TAG_SYNCHRONIZER = 0x39;
    public static final int WORMHOLE = 0x3a;
    public static final int QUEST = 0x3b;
    public static final int CONNECTOR_HOOK = 0x3c;
    public static final int ATMOSHPERIC_TWEAK = 0x3d;
    public static final int STREAMING_DATA = 0x3e;
    public static final int STREAMING_HINT = 0x3f;
}
