package toolkit.windows;

import java.awt.BorderLayout;
import java.io.File;

public class CharmyBee extends javax.swing.JFrame {
    
    public CharmyBee() 
    {
        initComponents();
        doProfileTest();
    }
    
    public void doProfileTest()
    {

        var panel = SaveManagerPanel.loadVitaProfile(new File("C:\\Users\\Aidan\\AppData\\Roaming\\Vita3K\\Vita3K\\ux0\\user\\00\\savedata\\PCSA00017"));
        _jTabPanel.add("profile0", panel);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _jRootPanel = new javax.swing.JPanel();
        _jTabPanel = new javax.swing.JTabbedPane();
        _jStatusPanel = new javax.swing.JPanel();
        _jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1397, 645));

        javax.swing.GroupLayout _jRootPanelLayout = new javax.swing.GroupLayout(_jRootPanel);
        _jRootPanel.setLayout(_jRootPanelLayout);
        _jRootPanelLayout.setHorizontalGroup(
            _jRootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_jTabPanel)
        );
        _jRootPanelLayout.setVerticalGroup(
            _jRootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_jTabPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        _jStatusPanel.setMaximumSize(new java.awt.Dimension(32767, 23));
        _jStatusPanel.setMinimumSize(new java.awt.Dimension(0, 23));
        _jStatusPanel.setPreferredSize(new java.awt.Dimension(0, 23));

        javax.swing.GroupLayout _jStatusPanelLayout = new javax.swing.GroupLayout(_jStatusPanel);
        _jStatusPanel.setLayout(_jStatusPanelLayout);
        _jStatusPanelLayout.setHorizontalGroup(
            _jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1397, Short.MAX_VALUE)
        );
        _jStatusPanelLayout.setVerticalGroup(
            _jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        _jMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        _jMenuBar.add(jMenu2);

        setJMenuBar(_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_jRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_jStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(_jRootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(_jStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar _jMenuBar;
    private javax.swing.JPanel _jRootPanel;
    private javax.swing.JPanel _jStatusPanel;
    private javax.swing.JTabbedPane _jTabPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
